### ISSUE TITLE
Roadmap for 0.5

### ISSUE THREAD

**Issue by keks** [ipfs/go-ipfs-cmds#21]
- [x] #3 Make Request pretty
- [x] #20 Remove go-ipfs deps
  - [x] extract legacy pacakge
  - [x] legacy: the user of cmds has to convert a `"go-ipfs"/command.Command` to a `"go-ipfs-cmds".Command` themselves using the legacy package
    - before `cmds.Command` had two maps for subcommands, one with `cmds.Command` values and one with `commands.Command` values
  - [x] move legacy to go-ipts/commands/legacy
  - [x] go-ipfs-cmds/http depends on go-ipfs/repo/config to get ipfs' version https://github.com/ipfs/go-ipfs-cmds/commit/ce22f514c6e161a6eb905187d33e259a511317be
    - let the caller set a user agent
    - let the caller set a version string that needs to be the same on client and server

- [x] cmdkit: rename Option.Default to WithDefault and Option.DefaultVal to Default
- [x] cmdkit: when an option is passed, only use the first (i.e. long) flag name as key in the map, instead of every name
  - this one requires changes all over go-ipfs-cmds, go-ipfs-cmdkit, go-ipfs/commands, go-ipfs/core/commands
  - [x] go-ipfs-cmdkit ipfs/go-ipfs-cmdkit@a03ffa728effdde07d32261400ba09855b520b60
  - [x] go-ipfs-cmds df00b75bfbb2ced28b37ee4b48b7a0b4ef8332c2
  - [x] go-ipfs/commands
  - [x] go-ipfs/core/commands
- [x] drop globalOptions, instead add them as Options to the root command
- [x] move predefined options from cmdkit to cmds
- [ ] make the legacy layer work again after all these changes
  - this one will be bad

Working branches:
- https://github.com/ipfs/go-ipfs-cmds/tree/cmds0.5
- https://github.com/ipfs/go-ipfs/tree/feat/cmds0.5
- https://github.com/ipfs/go-ipfs-cmdkit/tree/cmdkit1.0
